### ISSUE TITLE
Update PdfBox-Android binding to last version

### ISSUE THREAD

**Issue by 4brunu** [gsgou/Xamarin.Android.PdfBox#1]
Hey @gsgou,

First of all, thanks for this Xamarin binding.

Could you please update the binding PdfBox-Android to support version 1.8.10.3?
https://github.com/TomRoush/PdfBox-Android/releases/tag/v1.8.10.3

Thanks

**Comment by gsgou** [comment]
Tks a lot for this info. I ll try do it later today. In case takes more effort will leave it for the weekend and ping you here.

**Comment by 4brunu** [comment]
Thanks for you quick response and action 🙂

**Comment by 4brunu** [comment]
@gsgou any news on this? Can I help with this? 🙂

**Comment by 4brunu** [comment]
Hi @gsgou I created https://github.com/gsgou/Xamarin.Android.PdfBox/pull/2 that fixes this issue 🙂

**Comment by gsgou** [comment]
@4brunu thats really cool, thanks for tackling it. I ll check quick and update the nuget and add you in the contibutors of this wrapper :)

**Comment by 4brunu** [comment]
Hi @gsgou, would you have a change to review the two PR (https://github.com/gsgou/Xamarin.Android.PdfBox/pull/2 https://github.com/gsgou/Xamarin.Android.PdfBox/pull/3) and release a new version to nuget this week?
I need to create a new version of my app, but I'm pending on this.
Thanks 😊

**Comment by gsgou** [comment]
I understand you are on it. I ll Take the time today afterworks. Thanks a lot.

**Comment by 4brunu** [comment]
Thank you 🙂

**Comment by gsgou** [comment]
@4brunu just submitted a new nuget with your changes. Should be listed in couple hours. Thanks for contributing :)

**Comment by 4brunu** [comment]
Nice!
Thank you for taking the time to review and publish this new version! 👍

**Comment by gsgou** [comment]
I am glad was useful to somebody. I needed it for a project to parse texts and was the only way to do it for free by that time.
